#define yy_create_buffer FtaParser_create_buffer
#define yy_delete_buffer FtaParser_delete_buffer
#define yy_scan_buffer FtaParser_scan_buffer
#define yy_scan_string FtaParser_scan_string
#define yy_scan_bytes FtaParser_scan_bytes
#define yy_flex_debug FtaParser_flex_debug
#define yy_init_buffer FtaParser_init_buffer
#define yy_flush_buffer FtaParser_flush_buffer
#define yy_load_buffer_state FtaParser_load_buffer_state
#define yy_switch_to_buffer FtaParser_switch_to_buffer
#define yyin FtaParserin
#define yyleng FtaParserleng
#define yylex FtaParserlex
#define yyout FtaParserout
#define yyrestart FtaParserrestart
#define yytext FtaParsertext

#line 19 "ftalexer.cc"
/* A lexical scanner generated by flex*/

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* Some routines like yy_flex_realloc() are emitted as static but are
   not called by all lexers. This generates warnings in some compilers,
   notably GCC. Arrange to suppress these. */
#ifdef __GNUC__
#define YY_MAY_BE_UNUSED __attribute__((unused))
#else
#define YY_MAY_BE_UNUSED
#endif

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t )) YY_MAY_BE_UNUSED;
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yytext_ptr -= yy_more_len; \
	yyleng = (int) (yy_cp - yytext_ptr); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 85
#define YY_END_OF_BUFFER 86
static yyconst short int yy_accept[655] =
    {   0,
        0,    0,   86,   84,   81,   80,   66,   84,   67,   66,
       66,   70,   57,   62,   60,   63,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   45,   46,   68,   81,   80,    0,   79,   78,
        0,   74,    0,    0,   73,   70,    0,    0,   58,   64,
       61,   65,   59,   69,   69,   26,   69,   69,   69,   10,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   27,   69,

       27,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   29,   69,   29,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   27,   69,
       69,   69,   69,   69,   29,   69,   69,   69,   69,   69,
       69,   69,   69,    0,   82,    0,   77,    0,   83,   73,
        0,    0,   75,   71,    1,    5,    1,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       50,   69,   69,   69,   69,   69,   39,   69,   69,   69,

       69,   69,   69,   69,   69,   69,    7,   69,    6,   69,
       28,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,    8,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,    1,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,    0,   76,   72,   69,   69,   69,
       69,   69,   19,   69,   69,   69,   69,   69,   69,   69,
       11,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   40,   69,   69,   69,   69,   69,   69,   69,

       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   32,   69,   69,   69,   69,   33,   69,   36,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,    9,   69,   69,   69,
       37,   69,   69,   69,   17,   17,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   34,   69,   69,   69,   69,
       69,   44,   69,   69,   69,   69,   69,   69,   35,   69,
       69,   69,   69,   69,   47,   69,   69,   31,   69,   69,
       69,   69,   69,   69,   17,   69,   69,   69,   69,   69,

       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   43,   54,   69,   69,   69,   69,   25,   69,   69,
       41,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   18,   69,   30,   49,   69,   69,   30,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,    3,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   38,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,    2,   69,

       69,   69,   69,   69,   69,   69,   69,   69,   42,   69,
       69,   69,   52,   69,   69,   48,   69,   69,   69,   69,
       69,   69,   69,    4,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   12,   69,   69,   69,   13,   69,
       69,   69,   55,   21,   69,   69,   69,   69,   69,   69,
       69,   69,   23,   69,   69,   69,   69,   16,   69,   69,

       69,   69,   69,   69,   69,   69,   51,   69,   69,   69,
       69,   69,   69,   24,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   22,   20,   69,
       69,   53,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   15,   69,   69,   69,   69,   14,
       69,   69,   56,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    4,    4,    4,    4,    5,    4,
        4,    4,    6,    4,    7,    8,    9,   10,   10,   10,
       10,   10,   10,   11,   10,   10,   10,    4,   12,   13,
       14,   15,    1,    4,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
        4,    1,    4,    1,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   52,   41,   53,   54,   55,
       56,   57,   41,   58,   59,   60,   61,   62,   63,   64,
       65,   41,   66,    4,   67,   68,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[69] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        3,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    1,    1,    1
    } ;

static yyconst short int yy_base[660] =
    {   0,
        0,    0,  777,  778,  774,    0,  778,   66,  768,   62,
      765,   66,  778,   65,  778,   69,   56,   30,   61,  753,
        0,   65,   54,   76,   70,   83,  104,   75,   96,   88,
      109,  114,  119,  743,   87,  106,  104,  706,   92,  113,
      712,  726,  713,  720,  125,  710,  109,  122,   47,  715,
      714,  707,  778,  778,  778,  760,    0,  135,  778,  778,
      758,  169,  175,  757,  173,  186,  181,  732,  778,  778,
      778,  778,  778,    0,  739,    0,  735,  710,  706,    0,
      126,  718,  736,  143,  691,  707,  729,  722,  175,  718,
      731,  693,  689,  714,  687,  705,  702,  678,  710,  161,

      683,  716,  716,  687,  695,  700,  703,  667,  672,  674,
      693,  667,  706,  683,  689,  681,  662,  688,  690,  697,
      691,  668,  663,  688,  698,  680,  183,  659,  164,  694,
      694,  681,  672,  664,  675,  685,  657,  670,  644,  655,
      651,  157,  638,  654,  644,  640,  639,  632,  638,  644,
      627,  632,  634,  628,  645,  626,  636,  631,  630,  170,
      639,  634,  622,  676,  778,  197,  215,  675,  778,  218,
      224,  226,  229,  650,  634,    0,  633,  658,  639,  643,
      651,  627,  610,  613,  620,  642,  631,  637,  628,  634,
        0,  601,  606,  623,  597,  633,    0,  605,  635,  643,

      616,  641,  604,  615,  610,  588,    0,  625,    0,  597,
        0,  612,  628,  623,  626,  594,  624,  604,  615,  610,
      586,  582,  614,  615,  612,  599,  607,    0,  609,  581,
      577,  579,  598,  589,  603,  602,  561,  604,  586,  560,
      575,  574,  573,  571,  554,  557,  564,  550,  555,  547,
      556,  559,  545,  555,  560,  555,  551,  547,  552,  548,
      550,  536,  537,  552,  231,  233,  778,  577,  576,  562,
      566,  554,    0,  533,  536,  526,  556,  564,  564,  562,
        0,  534,  549,  522,  549,  522,  543,  533,  558,  531,
      514,  529,    0,  528,  549,  521,  551,  544,  532,  515,

      505,  534,  531,  525,  523,  498,  496,  538,  529,  538,
      517,    0,  519,  506,  492,  529,    0,  511,    0,  529,
      526,  498,  528,  527,  499,  486,  489,  479,  491,  480,
      481,  477,  492,  486,  483,  473,  470,  468,  483,  469,
      479,  482,  502,  474,  498,  492,    0,  469,  464,  498,
        0,  483,  483,  457,  490,  462,  490,  462,  468,  472,
      481,  470,  464,  475,  474,    0,  468,  480,  459,  451,
      457,    0,  480,  455,  465,  453,  437,  458,    0,  464,
      471,  468,  429,  439,    0,  471,  460,    0,  463,  435,
      434,  431,  426,  422,  428,  429,  435,  420,  426,  432,

      431,  415,  411,  421,  420,  446,  418,  437,  443,  409,
      414,    0,    0,  420,  419,  431,  404,    0,  433,  441,
        0,  440,  430,  418,  392,  422,  418,  425,  391,  423,
      417,  416,    0,  415,  420,    0,  410,  409,    0,  383,
      413,  397,  416,  388,  387,  380,  385,  391,  377,  379,
      369,  371,  376,  371,  368,  376,  391,  365,  400,  379,
      371,  377,  393,  392,  394,  366,  384,  386,  385,  355,
      375,  349,  375,    0,  377,  350,  378,  368,  342,  372,
      377,  370,  343,    0,  377,  364,  338,  337,  345,  351,
      340,  342,  334,  329,  332,  326,  330,  327,    0,  342,

      345,  340,  343,  350,  323,  336,  335,  352,    0,  324,
      354,  326,  330,  347,  319,    0,  334,  308,  338,  346,
      329,  303,  345,    0,  320,  298,  304,  317,  307,  310,
      305,  295,  293,  215,  330,  228,  302,  327,  299,  315,
      314,  318,  291,  312,  286,  306,  313,  286,  320,  292,
      296,  303,  305,  278,  305,   63,  283,  281,  272,  275,
      271,  273,  280,  269,  285,  301,  303,  257,  271,  273,
      290,  263,  297,  269,    0,  273,  272,  289,    0,  279,
      253,  279,    0,    0,  275,  243,  257,  259,  250,  257,
      261,  244,    0,  281,  271,  252,  243,    0,  262,  236,

      270,  269,  273,  250,  249,  254,    0,  242,  233,  227,
      234,  243,  255,    0,  228,  248,  222,  250,  223,   37,
      119,  133,  140,  122,  146,  154,  160,    0,    0,  193,
      168,    0,  216,  191,  225,  198,  194,  222,  197,  230,
      204,  237,  202,  207,    0,  230,  205,  231,  207,    0,
      225,  235,    0,  778,  266,  269,  265,  272,  275
    } ;

static yyconst short int yy_def[660] =
    {   0,
      654,    1,  654,  654,  654,  655,  654,  656,  654,  654,
      654,  654,  654,  654,  654,  654,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  654,  654,  654,  654,  655,  656,  654,  654,
      658,  654,  654,  659,  654,  654,  654,  654,  654,  654,
      654,  654,  654,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,

      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  658,  654,  654,  654,  659,  654,  654,
      654,  654,  654,  654,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,

      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  654,  654,  654,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,

      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,

      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,

      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,

      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,  657,  657,  657,  657,  657,  657,  657,
      657,  657,  657,    0,  654,  654,  654,  654,  654
    } ;

static yyconst short int yy_nxt[847] =
    {   0,
        4,    5,    6,    7,    8,    7,    9,   10,   11,   12,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   21,   21,   26,   27,   28,   29,
       30,   21,   31,   32,   33,   34,   21,   35,   36,   21,
       21,   21,   37,   38,   39,   21,   21,   40,   41,   42,
       43,   21,   44,   45,   46,   47,   21,   48,   49,   50,
       21,   21,   51,   52,   21,   53,   54,   55,   59,   80,
       60,   62,   62,   65,  632,   66,   66,   69,   70,   71,
       88,   63,   72,   73,   75,   67,   94,   81,   89,   76,
       82,   96,   77,  159,   80,   97,   83,   90,   99,   91,

      100,   68,  102,  118,  111,  103,  586,  160,   63,  136,
       78,   95,   67,   84,   76,   92,   85,   79,   98,  105,
      119,   86,   93,  106,  101,  587,  113,  107,  114,  104,
      112,  115,  120,  124,  130,  138,  137,   59,  121,   60,
      125,  131,  132,  633,  142,  178,  108,  143,  126,  127,
      109,  133,  144,  116,  110,  179,  117,  634,  140,  122,
      128,  139,   76,  145,  123,  141,  155,  151,  134,  156,
      146,  152,  157,  635,  129,  153,  628,  158,   62,   62,
      166,  166,  170,  170,  167,  167,  172,  172,   63,  182,
      173,  173,  171,   65,  188,   66,   66,  200,  183,  226,

      227,  189,  201,  244,  629,   67,  167,  167,  231,  636,
      228,  637,  245,  229,  260,   63,  638,  228,  639,  171,
      232,   68,  202,  228,  167,  167,  261,  170,  170,  265,
      265,  565,   67,  266,  266,  173,  173,  171,  173,  173,
      266,  266,  266,  266,  568,  640,  641,  642,  643,  644,
      645,  645,  566,  646,  647,  648,  645,  649,  650,  650,
      651,  650,  652,  653,  171,  569,   57,   74,   57,   58,
       58,   58,  164,  164,  164,  168,  168,  168,  631,  630,
      629,  629,  628,  628,  627,  626,  625,  614,  624,  623,
      622,  621,  620,  619,  618,  617,  616,  614,  615,  614,

      613,  612,  611,  610,  598,  609,  608,  593,  607,  606,
      605,  604,  603,  602,  601,  600,  599,  598,  598,  597,
      596,  593,  595,  594,  593,  584,  592,  579,  591,  575,
      590,  589,  588,  585,  584,  584,  583,  582,  581,  580,
      579,  579,  578,  577,  576,  575,  575,  574,  573,  572,
      571,  570,  567,  564,  563,  562,  561,  560,  559,  558,
      557,  556,  555,  554,  553,  552,  551,  550,  549,  548,
      547,  546,  545,  544,  543,  542,  541,  540,  539,  538,
      537,  536,  535,  534,  524,  533,  532,  531,  530,  529,
      528,  527,  526,  525,  499,  524,  524,  523,  522,  521,

      520,  519,  518,  517,  516,  515,  514,  513,  512,  511,
      510,  509,  509,  508,  507,  506,  505,  504,  503,  502,
      501,  500,  499,  499,  498,  497,  496,  495,  474,  494,
      493,  492,  491,  490,  489,  488,  487,  486,  485,  484,
      483,  482,  481,  480,  479,  478,  477,  476,  474,  475,
      474,  473,  472,  471,  470,  469,  468,  467,  466,  465,
      464,  463,  462,  461,  460,  459,  458,  457,  456,  455,
      439,  433,  454,  453,  452,  451,  450,  418,  449,  448,
      447,  446,  445,  444,  443,  442,  441,  440,  439,  438,
      437,  436,  435,  433,  434,  433,  432,  431,  430,  429,

      428,  427,  426,  425,  424,  423,  422,  421,  420,  419,
      418,  418,  417,  416,  415,  414,  413,  412,  411,  410,
      409,  408,  407,  406,  405,  388,  404,  403,  402,  401,
      400,  399,  366,  398,  397,  396,  395,  394,  347,  393,
      392,  391,  390,  389,  388,  388,  387,  386,  385,  384,
      383,  382,  381,  380,  379,  378,  377,  376,  375,  374,
      373,  372,  371,  370,  369,  368,  367,  366,  366,  365,
      364,  363,  362,  361,  360,  359,  358,  357,  356,  355,
      354,  353,  352,  351,  350,  347,  349,  348,  347,  346,
      345,  344,  343,  342,  341,  317,  340,  312,  339,  338,

      337,  336,  335,  334,  333,  332,  331,  330,  281,  329,
      273,  328,  327,  326,  325,  324,  323,  322,  321,  320,
      317,  319,  318,  317,  316,  315,  312,  314,  313,  312,
      311,  310,  309,  308,  307,  306,  305,  304,  303,  302,
      301,  300,  299,  298,  297,  296,  295,  294,  293,  292,
      291,  290,  289,  288,  287,  286,  285,  284,  283,  281,
      282,  281,  280,  279,  278,  277,  273,  276,  275,  274,
      273,  272,  271,  270,  269,  268,  267,  169,  165,  264,
      263,  262,  259,  258,  257,  256,  255,  211,  209,  254,
      207,  253,  252,  251,  250,  249,  248,  247,  246,  176,

      243,  242,  241,  240,  239,  238,  237,  236,  235,  234,
      233,  230,  225,  224,  223,  222,  221,  220,  219,  218,
      217,  216,  215,  214,  213,  212,  211,  211,  209,  210,
      207,  209,  208,  207,  206,  205,  204,  203,  199,  198,
      197,  196,  195,  194,  193,  192,  191,  190,  187,  186,
      185,  184,  181,  180,  176,  177,  176,  175,  174,  169,
      165,   56,  163,  162,  161,  154,  150,  149,  148,  147,
       80,  135,   87,   64,   61,   56,  654,    3,  654,  654,
      654,  654,  654,  654,  654,  654,  654,  654,  654,  654,
      654,  654,  654,  654,  654,  654,  654,  654,  654,  654,

      654,  654,  654,  654,  654,  654,  654,  654,  654,  654,
      654,  654,  654,  654,  654,  654,  654,  654,  654,  654,
      654,  654,  654,  654,  654,  654,  654,  654,  654,  654,
      654,  654,  654,  654,  654,  654,  654,  654,  654,  654,
      654,  654,  654,  654,  654,  654
    } ;

static yyconst short int yy_chk[847] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    8,   18,
        8,   10,   10,   12,  620,   12,   12,   14,   14,   14,
       22,   10,   16,   16,   17,   12,   23,   19,   22,   17,
       19,   24,   17,   49,   18,   24,   19,   22,   25,   22,

       25,   12,   26,   30,   28,   26,  556,   49,   10,   35,
       17,   23,   12,   19,   17,   22,   19,   17,   24,   27,
       30,   19,   22,   27,   25,  556,   29,   27,   29,   26,
       28,   29,   31,   32,   33,   36,   35,   58,   31,   58,
       32,   33,   33,  621,   39,   81,   27,   39,   32,   32,
       27,   33,   39,   29,   27,   81,   29,  622,   37,   31,
       32,   36,   37,   40,   31,   37,   47,   45,   33,   47,
       40,   45,   48,  623,   32,   45,  624,   48,   62,   62,
       63,   63,   65,   65,   63,   63,   67,   67,   62,   84,
       67,   67,   65,   66,   89,   66,   66,  100,   84,  127,

      127,   89,  100,  142,  625,   66,  166,  166,  129,  626,
      127,  627,  142,  127,  160,   62,  630,  129,  631,   65,
      129,   66,  100,  160,  167,  167,  160,  170,  170,  171,
      171,  534,   66,  171,  171,  172,  172,  170,  173,  173,
      265,  265,  266,  266,  536,  633,  634,  635,  636,  637,
      638,  639,  534,  640,  641,  642,  643,  644,  646,  647,
      648,  649,  651,  652,  170,  536,  655,  657,  655,  656,
      656,  656,  658,  658,  658,  659,  659,  659,  619,  618,
      617,  616,  615,  613,  612,  611,  610,  609,  608,  606,
      605,  604,  603,  602,  601,  600,  599,  597,  596,  595,

      594,  592,  591,  590,  589,  588,  587,  586,  585,  582,
      581,  580,  578,  577,  576,  574,  573,  572,  571,  570,
      569,  568,  567,  566,  565,  564,  563,  562,  561,  560,
      559,  558,  557,  555,  554,  553,  552,  551,  550,  549,
      548,  547,  546,  545,  544,  543,  542,  541,  540,  539,
      538,  537,  535,  533,  532,  531,  530,  529,  528,  527,
      526,  525,  523,  522,  521,  520,  519,  518,  517,  515,
      514,  513,  512,  511,  510,  508,  507,  506,  505,  504,
      503,  502,  501,  500,  498,  497,  496,  495,  494,  493,
      492,  491,  490,  489,  488,  487,  486,  485,  483,  482,

      481,  480,  479,  478,  477,  476,  475,  473,  472,  471,
      470,  469,  468,  467,  466,  465,  464,  463,  462,  461,
      460,  459,  458,  457,  456,  455,  454,  453,  452,  451,
      450,  449,  448,  447,  446,  445,  444,  443,  442,  441,
      440,  438,  437,  435,  434,  432,  431,  430,  429,  428,
      427,  426,  425,  424,  423,  422,  420,  419,  417,  416,
      415,  414,  411,  410,  409,  408,  407,  406,  405,  404,
      403,  402,  401,  400,  399,  398,  397,  396,  395,  394,
      393,  392,  391,  390,  389,  387,  386,  384,  383,  382,
      381,  380,  378,  377,  376,  375,  374,  373,  371,  370,

      369,  368,  367,  365,  364,  363,  362,  361,  360,  359,
      358,  357,  356,  355,  354,  353,  352,  350,  349,  348,
      346,  345,  344,  343,  342,  341,  340,  339,  338,  337,
      336,  335,  334,  333,  332,  331,  330,  329,  328,  327,
      326,  325,  324,  323,  322,  321,  320,  318,  316,  315,
      314,  313,  311,  310,  309,  308,  307,  306,  305,  304,
      303,  302,  301,  300,  299,  298,  297,  296,  295,  294,
      292,  291,  290,  289,  288,  287,  286,  285,  284,  283,
      282,  280,  279,  278,  277,  276,  275,  274,  272,  271,
      270,  269,  268,  264,  263,  262,  261,  260,  259,  258,

      257,  256,  255,  254,  253,  252,  251,  250,  249,  248,
      247,  246,  245,  244,  243,  242,  241,  240,  239,  238,
      237,  236,  235,  234,  233,  232,  231,  230,  229,  227,
      226,  225,  224,  223,  222,  221,  220,  219,  218,  217,
      216,  215,  214,  213,  212,  210,  208,  206,  205,  204,
      203,  202,  201,  200,  199,  198,  196,  195,  194,  193,
      192,  190,  189,  188,  187,  186,  185,  184,  183,  182,
      181,  180,  179,  178,  177,  175,  174,  168,  164,  163,
      162,  161,  159,  158,  157,  156,  155,  154,  153,  152,
      151,  150,  149,  148,  147,  146,  145,  144,  143,  141,

      140,  139,  138,  137,  136,  135,  134,  133,  132,  131,
      130,  128,  126,  125,  124,  123,  122,  121,  120,  119,
      118,  117,  116,  115,  114,  113,  112,  111,  110,  109,
      108,  107,  106,  105,  104,  103,  102,  101,   99,   98,
       97,   96,   95,   94,   93,   92,   91,   90,   88,   87,
       86,   85,   83,   82,   79,   78,   77,   75,   68,   64,
       61,   56,   52,   51,   50,   46,   44,   43,   42,   41,
       38,   34,   20,   11,    9,    5,    3,  654,  654,  654,
      654,  654,  654,  654,  654,  654,  654,  654,  654,  654,
      654,  654,  654,  654,  654,  654,  654,  654,  654,  654,

      654,  654,  654,  654,  654,  654,  654,  654,  654,  654,
      654,  654,  654,  654,  654,  654,  654,  654,  654,  654,
      654,  654,  654,  654,  654,  654,  654,  654,  654,  654,
      654,  654,  654,  654,  654,  654,  654,  654,  654,  654,
      654,  654,  654,  654,  654,  654
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() (yy_more_flag = 1)
#define YY_MORE_ADJ yy_more_len
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "fta.l"
#define INITIAL 0
/*
	MUST COMPILE WITH
		flex -PFtaParser -oftalexer.cc fta.l
	(or equivalent).
*/	
#line 9 "fta.l"
/*
 * AT&T lex can't handle this lexer due to lex bugs.  It works with flex
 * 2.3.7, pclex 2.0.5, and MKS lex 3.1a.
 */

 #include "parse_fta.h"
 #include "parse_schema.h"
 #include <string.h>



#include "fta.tab.cc.h"

/*
	Some includes that flex doesn't include as standard,
	but which are needed.
*/

#include <stdlib.h>
#include <string.h>


//		Prevent flex from defining yywrap as extern "C" 

#define YY_SKIP_YYWRAP

/*		No lex lib, supply the yywrap fcn. that normally resides there
*/

int FtaParserwrap(){return(1);}

extern int FtaParserdebug;


/*
		These variables are used for error reporting:
		flex_fta_lineno : the line currently being parsed when the error occurs.
		flex_fta_ch : the character on the line where the error occurs
		flex_fta_linebuf : store the line for reporting.

		NOTE : 1) the fixed size flex_fta_linebuf buffer is dangerous.
			   2) You might get pointed to a place shortly after
			 	  where the syntax error occurs.  It is close enough
				  for now.
*/

int flex_fta_lineno = 1;
int flex_fta_ch = 0;
char flex_fta_linebuf[200000];

char *flex_fta_stringinput = NULL;
int flex_fta_stringinput_ptr = 0;
FILE *flex_fta_fileinput = NULL;
int my_FtaParser_yyinput(char *buf, int max_size);



void FtaParsererror(char *s){
	int i;
	fprintf(stderr,"On line %d, char %d: %s (token %s):\n%s\n",
				flex_fta_lineno, flex_fta_ch, s, FtaParsertext, flex_fta_linebuf );
    for(i=0;i<flex_fta_ch;i++){
		if(flex_fta_linebuf[i] == '\t'){
			fprintf(stderr,"\t");
		}else{
			fprintf(stderr," ");
		}
	}
	fprintf(stderr,"^\n");
	//	fprintf(stderr,"%*s\n",1+flex_fta_ch,"^");
}

#undef YY_INPUT
#define YY_INPUT(b, r, ms) (r = my_FtaParser_yyinput(b,ms))

/* MKS needs the next line to increase the NFA table */
#line 881 "ftalexer.cc"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 89 "fta.l"


	/* literal keyword tokens */

 /*
			The actions associated with each text token are to
			keep track of the current location (for syntax error reporting)
			and to report any necessary info to the emf.y parse tree builder

			Its likely that there are a number of omissions, inconsistencies
			(some keywords do not need to be in caps), and relics
			(keywords such as BETWEEN, INDICATOR, etc., are not used
			 in emf.y)
			This parser is somewhat of a work in progress.
 */

 /*		Query keywords		*/

#line 1051 "ftalexer.cc"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_more_len = 0;
		if ( yy_more_flag )
			{
			yy_more_len = yy_c_buf_p - yytext_ptr;
			yy_more_flag = 0;
			}
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 655 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 778 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 107 "fta.l"
{ flex_fta_ch+=FtaParserleng; return AND; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 108 "fta.l"
{ flex_fta_ch+=FtaParserleng; FtaParserlval.strval = strdup("AND_AGGR"); return AGGR; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 109 "fta.l"
{ flex_fta_ch+=FtaParserleng; FtaParserlval.strval = strdup("OR_AGGR"); return AGGR; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 110 "fta.l"
{ flex_fta_ch+=FtaParserleng; FtaParserlval.strval = strdup("XOR_AGGR"); return AGGR; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 111 "fta.l"
{ flex_fta_ch+=FtaParserleng; FtaParserlval.strval = strdup("AVG"); return AGGR; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 112 "fta.l"
{ flex_fta_ch+=FtaParserleng; FtaParserlval.strval = strdup("MIN"); return AGGR; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 113 "fta.l"
{ flex_fta_ch+=FtaParserleng; FtaParserlval.strval = strdup("MAX"); return AGGR; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 114 "fta.l"
{ flex_fta_ch+=FtaParserleng; FtaParserlval.strval = strdup("SUM"); return AGGR; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 115 "fta.l"
{ flex_fta_ch+=FtaParserleng; FtaParserlval.strval = strdup("COUNT"); return AGGR; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 116 "fta.l"
{ flex_fta_ch+=FtaParserleng; return BY; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 117 "fta.l"
{ flex_fta_ch+=FtaParserleng; return FROM; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 118 "fta.l"
{ flex_fta_ch+=FtaParserleng; return INNER_JOIN; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 119 "fta.l"
{ flex_fta_ch+=FtaParserleng; return OUTER_JOIN; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 120 "fta.l"
{ flex_fta_ch+=FtaParserleng; return RIGHT_OUTER_JOIN; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 121 "fta.l"
{ flex_fta_ch+=FtaParserleng; return LEFT_OUTER_JOIN; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 122 "fta.l"
{ flex_fta_ch+=FtaParserleng; return FILTER_JOIN; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 123 "fta.l"
{ flex_fta_ch+=FtaParserleng; return GROUP; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 124 "fta.l"
{ flex_fta_ch+=FtaParserleng; return ROLLUP; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 125 "fta.l"
{ flex_fta_ch+=FtaParserleng; return CUBE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 126 "fta.l"
{ flex_fta_ch+=FtaParserleng; return GROUPING_SETS; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 127 "fta.l"
{ flex_fta_ch+=FtaParserleng; return SUPERGROUP; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 128 "fta.l"
{ flex_fta_ch+=FtaParserleng; return CLEANING_WHEN; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 129 "fta.l"
{ flex_fta_ch+=FtaParserleng; return CLEANING_BY; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 130 "fta.l"
{ flex_fta_ch+=FtaParserleng; return CLOSING_WHEN; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 131 "fta.l"
{ flex_fta_ch+=FtaParserleng; return HAVING; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 132 "fta.l"
{ flex_fta_ch+=FtaParserleng; return AS; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 133 "fta.l"
{ flex_fta_ch+=FtaParserleng; return IN; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 134 "fta.l"
{ flex_fta_ch+=FtaParserleng; return NOT; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 135 "fta.l"
{ flex_fta_ch+=FtaParserleng; return OR; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 137 "fta.l"
{ flex_fta_ch+=FtaParserleng; return SELECT; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 138 "fta.l"
{ flex_fta_ch+=FtaParserleng; return WHERE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 139 "fta.l"
{ flex_fta_ch+=FtaParserleng; return SUCH;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 140 "fta.l"
{ flex_fta_ch+=FtaParserleng; return THAT;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 141 "fta.l"
{flex_fta_ch+=FtaParserleng; return MERGE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 142 "fta.l"
{flex_fta_ch+=FtaParserleng; return SLACK;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 144 "fta.l"
{ flex_fta_ch+=FtaParserleng; return TRUE_V;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 145 "fta.l"
{ flex_fta_ch+=FtaParserleng; return FALSE_V;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 146 "fta.l"
{ flex_fta_ch+=FtaParserleng; return TIMEVAL_L;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 147 "fta.l"
{ flex_fta_ch+=FtaParserleng; return HEX_L;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 148 "fta.l"
{ flex_fta_ch+=FtaParserleng; return LHEX_L;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 149 "fta.l"
{ flex_fta_ch+=FtaParserleng; return IP_L;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 150 "fta.l"
{ flex_fta_ch+=FtaParserleng; return IPV6_L;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 152 "fta.l"
{ flex_fta_ch+=FtaParserleng; return DEFINE_SEC;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 153 "fta.l"
{ flex_fta_ch+=FtaParserleng; return PARAM_SEC;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 155 "fta.l"
{flex_fta_ch+=FtaParserleng; return LEFTBRACE;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 156 "fta.l"
{flex_fta_ch+=FtaParserleng; return RIGHTBRACE;}
	YY_BREAK
/*
		Table definition keywords
 */		
case 47:
YY_RULE_SETUP
#line 161 "fta.l"
{ flex_fta_ch+=FtaParserleng; return TABLE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 162 "fta.l"
{ flex_fta_ch+=FtaParserleng; return PROTOCOL; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 163 "fta.l"
{ flex_fta_ch+=FtaParserleng; return STREAM; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 164 "fta.l"
{ flex_fta_ch+=FtaParserleng; return FTA; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 165 "fta.l"
{ flex_fta_ch+=FtaParserleng; return UNPACK_FCNS; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 167 "fta.l"
{ flex_fta_ch+=FtaParserleng; return OPERATOR; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 168 "fta.l"
{ flex_fta_ch+=FtaParserleng; return OPERATOR_VIEW; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 169 "fta.l"
{ flex_fta_ch+=FtaParserleng; return FIELDS; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 170 "fta.l"
{ flex_fta_ch+=FtaParserleng; return SUBQUERIES; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 171 "fta.l"
{ flex_fta_ch+=FtaParserleng; return SELECTION_PUSHDOWN; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 172 "fta.l"
{flex_fta_ch+=FtaParserleng; return SEMICOLON;}
	YY_BREAK
/* punctuation */
case 58:
#line 177 "fta.l"
case 59:
YY_RULE_SETUP
#line 177 "fta.l"
{ flex_fta_ch+=FtaParserleng; FtaParserlval.strval = strdup(yytext); return SHIFT_OP; }
	YY_BREAK
case 60:
#line 180 "fta.l"
case 61:
#line 181 "fta.l"
case 62:
#line 182 "fta.l"
case 63:
#line 183 "fta.l"
case 64:
#line 184 "fta.l"
case 65:
YY_RULE_SETUP
#line 184 "fta.l"
{ flex_fta_ch+=FtaParserleng; FtaParserlval.strval = strdup(yytext); return COMPARISON; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 186 "fta.l"
{ flex_fta_ch+=FtaParserleng; return yytext[0]; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 187 "fta.l"
{ flex_fta_ch+=FtaParserleng; return yytext[0]; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 188 "fta.l"
{ flex_fta_ch+=FtaParserleng; return yytext[0]; }
	YY_BREAK
/* names */
case 69:
YY_RULE_SETUP
#line 192 "fta.l"
{ flex_fta_ch+=FtaParserleng; FtaParserlval.strval = strdup(yytext); return NAME; }
	YY_BREAK
/* numbers */
case 70:
#line 197 "fta.l"
case 71:
YY_RULE_SETUP
#line 197 "fta.l"
{ flex_fta_ch+=FtaParserleng; FtaParserlval.strval = strdup(yytext);  return INTNUM; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 199 "fta.l"
{ flex_fta_ch+=FtaParserleng; FtaParserlval.strval = strdup(yytext);  return LONGINTNUM; }
	YY_BREAK
case 73:
#line 202 "fta.l"
case 74:
#line 203 "fta.l"
case 75:
#line 204 "fta.l"
case 76:
#line 205 "fta.l"
case 77:
YY_RULE_SETUP
#line 205 "fta.l"
{ flex_fta_ch+=FtaParserleng; FtaParserlval.strval = strdup(yytext); return APPROXNUM; }
	YY_BREAK
/* strings */
case 78:
YY_RULE_SETUP
#line 209 "fta.l"
{
		
		int c;
		
		FtaParserlval.strval = strdup(FtaParsertext+1); 

		c = yyinput();

		unput(c);	/* just peeking */
		if(c != '\'') {
			flex_fta_ch+=FtaParserleng; 
			FtaParserlval.strval[FtaParserleng-2] = '\0';
			return STRING_TOKEN;
		} else
			yymore();
	}
	YY_BREAK
case 79:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 226 "fta.l"
{ flex_fta_ch+=FtaParserleng; FtaParsererror("Unterminated string"); }
	YY_BREAK
/*															*/
/*		Newline : advance the error reporting line number	*/
/*		and grab the next line into flex_fta_linebuf			*/
/*															*/
case 80:
YY_RULE_SETUP
#line 233 "fta.l"
{flex_fta_ch=0; flex_fta_lineno++;
			   strcpy(flex_fta_linebuf,FtaParsertext+1);
			   yyless(1);
			   }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 238 "fta.l"
{flex_fta_ch+=FtaParserleng; }	/* white space */
	YY_BREAK
case 82:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 240 "fta.l"
{flex_fta_ch+=FtaParserleng; };	/* comment */
	YY_BREAK
case 83:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 241 "fta.l"
{flex_fta_ch+=FtaParserleng; };	/* comment */
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 243 "fta.l"
{flex_fta_ch+=FtaParserleng; fprintf(stderr,"Warning: unknown token (ignored)\n");  FtaParsererror(yytext);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 245 "fta.l"
ECHO;
	YY_BREAK
#line 1570 "ftalexer.cc"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 655 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 655 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 654);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 245 "fta.l"


int my_FtaParser_yyinput(char *buf, int max_size){
	int c = 0;
	int inchar = 0;
	
	if(flex_fta_stringinput != NULL){
		while(c<max_size){
			if(flex_fta_stringinput[flex_fta_stringinput_ptr] != '\0'){
				buf[c++] = flex_fta_stringinput[flex_fta_stringinput_ptr++];
			}else{
				break;
			}
		}
		return(c);
	}
	
	if(flex_fta_fileinput != NULL){
		while(c < max_size){
			inchar = getc(flex_fta_fileinput);
			if(inchar != EOF){
				buf[c++] = inchar;
			}else{
				break;
			}
		}
		return(c);
	}
	
	return(0);
}

void FtaParser_setfileinput(FILE *f){
	FtaParserrestart(NULL);

	flex_fta_fileinput = f;
	flex_fta_stringinput = NULL;
	flex_fta_lineno = 1;
	flex_fta_ch = 0;
}

void FtaParser_setstringinput(char *s){
	FtaParserrestart(NULL);

	flex_fta_fileinput = NULL;
	flex_fta_stringinput = s;
	flex_fta_stringinput_ptr = 0;
	flex_fta_lineno = 1;
	flex_fta_ch = 0;
}
	
		


