
all: mgscphost mgscphostaux mgscplftaaux mgscphftaaux mgscprts mgscpapp mgscpaux

clean:
	cd gscphost ; make clean
	cd gscphostaux ; make clean
	cd gscplftaaux ; make clean
	cd gscphftaaux ; make clean
	cd gscprts ; make clean
	cd gscpapp; make clean
	cd gscpaux; make clean

install:
	cd gscphost ; make install
	cd gscphostaux ; make install
	cd gscplftaaux ; make install
	cd gscphftaaux ; make install
	cd gscprts ; make install
	cd gscpapp; make install
	cd gscpaux; make install

mgscphost:
	cd gscphost ; make

mgscphostaux:
	cd gscphostaux ; make

mgscplftaaux:
	cd gscplftaaux ; make

mgscphftaaux:
	cd gscphftaaux ; make

mgscprts:
	cd gscprts ; make

mgscpapp:
	cd gscpapp; make

mgscpaux:
	cd gscpaux; make

